#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=cfn-custom-ec2-inst-detailed-monitorng@v1.0 defects=0}
Resources:
  ExampleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref pInstanceType
      IamInstanceProfile: !Ref rInstanceProfile
      # Compliant: `Monitoring` is set to `true`.
      Monitoring: true
# {/fact}
