#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=disabled-aurora-encryption-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBClusterIdentifier: !Ref AWS::StackName
      BackupRetentionPeriod: 35
      DeletionProtection: true
      EnableIAMDatabaseAuthentication: true
      # Noncompliant: `StorageEncrypted` is set to false.
      StorageEncrypted: false
      VpcSecurityGroupIds:
        - !Ref VpcSecurityGroupId
# {/fact}