#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=exposed-lambda-env-secret-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: AWS Lambda Function to initiate the chat with the end user
      Handler: "index.handler"
      Role: !GetAtt InitiateChatLambdaExecutionRole.Arn
      Runtime: "nodejs14.x"
      MemorySize: 128
      Timeout: 30
      Environment:
        # Noncompliant: hard-coded secrets exist in lambda environment.
        Variables:
          key1: AKIAAAAAAAAAAAAAAAAA
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref InitiateChatLambdaCodeObject
      ReservedConcurrentExecutions: 100
      DeadLetterConfig:
        TargetArn: "test"
      VpcConfig:
        SecurityGroupIds:
          - sg-12345
        SubnetIds:
          - subnet-12345
          - subnet-67890
      KmsKeyArn: arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab
# {/fact}
