#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=restrict-log4j2-msg-lookup-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: ${self:custom.environment.WAF_NAME}
      Description: Selfie2Anime Rate Limits
      DefaultAction:
        Allow: { }
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: rate-limits
      Scope: "REGIONAL"
      Rules:
        - Name: rate-limiter
          Priority: 0
          Action:
            Block: { }
          Statement:
            # Noncompliant: `ManagedRuleGroupStatement` is not present.
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: rate-limiter
# {/fact}
