#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=exposed-ec2-user-data-secret-cloudformation@v1.0 defects=0}
Resources:
  Resource:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: true
      ImageId: !Ref BastionImageId
      InstanceType: t2.nano
      KeyName: !Ref BastionKeyName
      Monitoring: false
      SecurityGroupIds:
        - !Ref VpcSecurityGroupId
        - !Ref BastionSecurityGroup
      # Compliant:  Hard-coded secrets don't exist in EC2 user data.
      UserData: !Base64 'yum install mysql --assumeyes'
# {/fact}
