#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=checkov-custom-ecs-task-definition@v1.0 defects=1}
Resources:
      TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
          NetworkMode: host
          ContainerDefinitions:
            Name: ContainerA
            User: root
            # Noncompliant: Amazon ECS task definition has privileged set to false
            Privileged: false
# {/fact}