#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=public-write-s3-bucket-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt InvokedFunction.Arn
      # Noncompliant: S3 bucket allows WRITE permissions to everyone.
      AccessControl: PublicReadWrite
      LoggingConfiguration:
        DestinationBucketName: String
        LogFilePrefix: String
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
# {/fact}
