#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=restrict-wildcard-kms-cloudformation@v1.0 defects=0}
Resources:
  Resource:
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub ${AWS::StackName}-${AWS::AccountId}-key-policy
        Statement:
          - Sid: Allow source account access to KMS key in source account
            Effect: Allow
            # Compliant: KMS key policy does not contain wildcard(*) principal.
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
# {/fact}
