#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=disabled-glue-cat-encrypt-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: 'AWS::Glue::DataCatalogEncryptionSettings'
    Properties:
      CatalogId: "CatalogId"
      DataCatalogEncryptionSettings:
        ConnectionPasswordEncryption:
          KmsKeyId: "KmsKeyId"
          ReturnConnectionPasswordEncrypted: True
        EncryptionAtRest:
          # Compliant: Glue Data Catalog Encryption is disabled.
          CatalogEncryptionMode: "Disabled"
          SseAwsKmsKeyId: "SseAwsKmsKeyId"
# {/fact}
