#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=disabled-neptune-logging-cloudformation@v1.0 defects=0}
Resources:
  Resource:
    Type: AWS::Neptune::DBCluster
    DependsOn: NeptuneDBSG
    Properties:
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DBClusterParameterGroupName: !Ref NeptuneDBClusterParameterGroup
      DBSubnetGroupName: !Ref NeptuneDBSubnetGroup
      IamAuthEnabled: !Ref IAMAuthEnabled
      Port: !Ref Port
      PreferredBackupWindow: !Ref NeptuneDBClusterPreferredBackupWindow
      PreferredMaintenanceWindow: !Ref NeptuneDBClusterPreferredMaintenanceWindow
      # Compliant: Neptune logging is enabled.
      EnableCloudwatchLogsExports: [ "audit" ]
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - !Ref 'NeptuneDBSG'
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${AppName}-Cluster'
# {/fact}
