#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=unsecure-encrypt-efs-cloudformation@v1.0 defects=1}
Resources:
  Resource:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - MountA
      - MountB
    Properties:
      Volumes:
        - Name: factorio
          # Noncompliant: Encryption in transit is not enabled.
          EFSVolumeConfiguration:
            FilesystemId: !Ref Efs
# {/fact}
